package chap14_exception;

public class _02_generateException {

	public static void main(String[] args) {
		
		try {
			/*ArrayIndexOutOfBoundsException aie 
			 = new ArrayIndexOutOfBoundsException("인덱스 초과");
			
			throw aie; */
			//1. NullPointerException
			if(true) {
				System.out.println(10/0);
			}
			//2. ArithmeticExeption
		} catch(NullPointerException ne) {
			System.out.println("계산오류");
		} catch(ArithmeticException ae) {
		
		//마지막 catch문은 위에서 선언한 catch문을 다 통과한 예외들을 
		//처리할 수 있게 모든 예외를 담을 수 있는 
	    //예외의 최상위 클래인 exception으로 처리해야 함.
		} catch(Exception e) { 
			System.out.println(e.getMessage());
		}
	}

}
